# Makefile

clean:
	rm -f ".o files" core ".exe/class files" "outputs"
	rm -f *.*~
	rm -f *~
	rm -f *.out
	rm -f MSS_Results.txt
	ls

MaxSubArray:
	python MaxSubArray.py MSS_Problems.txt
	cat MSS_Results.txt
